//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week_3_Intern_Assignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STOREFRONTEntitiesALL : DbContext
    {
        public STOREFRONTEntitiesALL()
            : base("name=STOREFRONTEntitiesALL")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address_table> Address_table { get; set; }
        public virtual DbSet<Order_table> Order_table { get; set; }
        public virtual DbSet<OrderProduct_table> OrderProduct_table { get; set; }
        public virtual DbSet<Product_table> Product_table { get; set; }
        public virtual DbSet<ShoppingCart_table> ShoppingCart_table { get; set; }
        public virtual DbSet<ShoppingCartProduct_table> ShoppingCartProduct_table { get; set; }
        public virtual DbSet<State_table> State_table { get; set; }
        public virtual DbSet<Status_table> Status_table { get; set; }
        public virtual DbSet<User_table> User_table { get; set; }
    }
}
