//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week_3_Intern_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_table
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProdDescription { get; set; }
        public bool isPublished { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal Price { get; set; }
        public string ImageFile { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
    }
}
