//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week_3_Intern_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_table
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public byte[] Password { get; set; }
        public string EmailAddress { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
    }
}
